ground_truths:
  drone_pose:
    name: drone_pose
    num_states: 6
    topic:
      sim: /ground_truth/helipad_frame/drone_pose
      real: /qualisys/anafi/pose
    file_header: "Format: timestamp[sec] x[m], y[m], z[m], phi[deg], theta[deg], psi[deg]]\n"
    max_values_stored_in_buffer: 10

  helipad_pose:
    name: helipad_pose
    num_states: 6
    topic:
      sim: /ground_truth/ned_frame/helipad_pose
      real: /qualisys/helipad/pose
    file_header: "Format: timestamp[sec] x[m], y[m], z[m], phi[deg], theta[deg], psi[deg]]\n"
    max_values_stored_in_buffer: 10

estimates:
  dnn_cv_position:
    name: dnn_cv_position
    num_states: 3
    topic:
      sim: /estimate/dnn_cv/position
      real: /estimate/dnn_cv/position
    file_header: "Format: timestamp[sec] [x[m], y[m], z[m]]\n"
    max_values_stored_in_buffer: 10

  dnn_cv_heading:
    name: dnn_cv_heading
    num_states: 1
    topic:
      sim: /estimate/dnn_cv/heading
      real: /estimate/dnn_cv/heading
    file_header: "Format: timestamp[sec] psi[deg]]\n"
    max_values_stored_in_buffer: 5

  tcv_pose:
    name: tcv_pose
    num_states: 6
    topic:
      sim: /estimate/drone_pose/tcv
      real: /estimate/drone_pose/tcv
    file_header: "Format: timestamp[sec] [x[m], y[m], z[m], phi[deg] theta[deg] psi[deg]]\n"
    max_values_stored_in_buffer: 1

  ekf_output:
    name: ekf_output
    num_states: 56 # 7 states + 7x7 covariance matrix
    topic:
      sim: /estimate/ekf
      real: /estimate/ekf
    file_header: "Format: timestamp[sec] [x_drone[m], y_drone[m], z_drone[m],
                  psi_drone[deg], vx_helipad[m/s], vx_helipad[m/s], vx_helipad[m/s],
                  covariance for each state (flattened 7x7 matrix)]\n"
    max_values_stored_in_buffer: 10
