yolo_model:

  config_file:
    name: yolov4-custom.cfg
  weight_file:
    name: ardrone_sim.weights
  threshold:
    value: 0.8
  detection_classes:
    names:
      - Arrow
      - H
      - Helipad
