yolo_model:

  config_file:
    name: yolov4-tiny-custom.cfg
  weight_file:
    name: yolov4-tiny-custom.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - H
      - Arrow
      - Helipad
