shi_tomasi:
  max_corners: 13
  quality_level: 0.01
  min_distance: 10
  block_size: 3
  gradient_size: 3
  k: 0.04

feature_dists_metric:
  path: "data/helipad_dists_origin_center_enu_metric.txt"

camera_matrix:
  path: "data/camera_matrix.txt"